# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package (self hosted)

on: [push, pull_request]
jobs:
  buildSelfHosted:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install pytest-custom-exit-code
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names. The GitHub editor is 127 chars wide
        flake8 ./scrapers --count --select=E9,F63,F7,F82 --show-source --max-line-length=127 --statistics
        # exit-zero treats all errors as warnings.
        flake8 ./scrapers --count --max-complexity=10 --statistics
    - name: Test pytest
      run: |
        chmod -R 777 ./
        pytest --suppress-no-test-exit-code
